<?xml version="1.0" encoding="UTF-8" ?>
<project
    xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
>
	<modelVersion>4.0.0</modelVersion>

	<groupId>ru.snake.collection</groupId>
	<artifactId>iddlite</artifactId>
	<version>1.0.0</version>
	<packaging>pom</packaging>

	<name>IDD Lite Parent</name>
	<description
    >Parent POM for Interval Decision Diagram library and benchmarks</description>

	<modules>
		<module>idd-core</module>
		<module>idd-firewall</module>
		<module>idd-benchmark</module>
	</modules>

	<properties>
		<maven.compiler.source>21</maven.compiler.source>
		<maven.compiler.target>21</maven.compiler.target>
		<maven.compiler.release>21</maven.compiler.release>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<junit.version>5.9.3</junit.version>
		<jmh.version>1.37</jmh.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>ru.snake.collection</groupId>
				<artifactId>idd-core</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>org.junit.jupiter</groupId>
				<artifactId>junit-jupiter</artifactId>
				<version>${junit.version}</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>org.openjdk.jmh</groupId>
				<artifactId>jmh-core</artifactId>
				<version>${jmh.version}</version>
			</dependency>
			<dependency>
				<groupId>org.openjdk.jmh</groupId>
				<artifactId>jmh-generator-annprocess</artifactId>
				<version>${jmh.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>
</project>
